language: python
python:
    - "2.7"
services:
  - redis-server
install:
    - make venv
    - pip install coveralls

script: sh runtests.sh

after_success: sh -c "ps aux | grep '/test.json' | awk '{print $2}' | xargs  kill" && coveralls