language: python
python:
    - "2.7"
    - "pypy"

install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install https://github.com/talkincode/toughlib/archive/master.zip --upgrade --no-deps
    - pip install https://github.com/talkincode/txradius/archive/master.zip --upgrade --no-deps

script: coverage run trial toughradius.tests
after_success: coveralls