raddb:
    image: "index.alauda.cn/toughstruct/mysql:M1"
    privileged: true
    expose:
        - "3306"
    environment:
        - MYSQL_USER=raduser
        - MYSQL_PASSWORD=radpwd
        - MYSQL_DATABASE=radiusd
        - MYSQL_ROOT_PASSWORD=radroot
    restart: always
    volumes:
        - /home/var/mysql:/var/lib/mysql

radius:
    build: .
    privileged: true
    ports:
        - "1816:1816"
    links:
        - raddb
    environment:
        - ROOT_PASSWORD=toughradius
        - DB_TYPE=mysql
        - DB_URL=mysql://raduser:radpwd@raddb:3306/radiusd?charset=utf8
        - TIMEZONE=CST-8
        - SYSLOG_ENABLE=1
        - SYSLOG_SERVER=121.201.15.99
        - SYSLOG_PORT=514
        - SYSLOG_LEVEL=INFO
    restart: always
    volumes:
        - /home/var/toughradius:/var/toughradius

engine:
    image: "index.alauda.cn/toughstruct/toughengine"
    privileged: true
    links:
        - radius
    ports:
        - "1812:1823/udp"
        - "1813:1813/udp"
        - "1815:1815"
    environment:
        - ROOT_PASSWORD=toughstruct
        - TIMEZONE=CST-8
        - API_URL=http://radius:1816/api
        - API_SECRET=LpWE9AtfDPQ3ufXBS6gJ37WW8TnSF920
        - SYSLOG_ENABLE=1
        - SYSLOG_SERVER=121.201.15.99
        - SYSLOG_PORT=514
        - SYSLOG_LEVEL=INFO
    restart: always
    volumes:
        - /home/var/toughengine:/var/toughengine

