raddb:
    image: "index.alauda.cn/toughstruct/mysql"
    privileged: true
    expose:
        - "3306"
    environment:
        - MYSQL_USER=raduser
        - MYSQL_PASSWORD=radpwd
        - MYSQL_DATABASE=radiusd
        - MYSQL_ROOT_PASSWORD=radroot
    restart: always
    volumes:
        - /home/toughrun/mysql:/var/lib/mysql

radius:
    image: "index.alauda.cn/toughstruct/toughradius:v2"
    command: pypy /opt/toughradius/toughctl --standalone
    expose:
        - "1816:1816"
        - "1812:1812/udp"
        - "1813:1813/udp"
    links:
        - raddb:raddb
    environment:
        - DB_TYPE=mysql
        - DB_URL=mysql://raduser:radpwd@raddb:3306/radiusd?charset=utf8
    restart: always
    volumes:
        - /home/toughrun/toughradius:/var/toughradius

haradius:
    image: "index.alauda.cn/tutum/haproxy"
    links:
        - radius:radius
    ports:
        - "1816:80"


