raddb:
    image: "index.alauda.cn/toughstruct/mysql:M1"
    privileged: true
    expose:
        - "3306"
    environment:
        - MYSQL_USER=raduser
        - MYSQL_PASSWORD=radpwd
        - MYSQL_DATABASE=radiusd
        - MYSQL_ROOT_PASSWORD=radroot
    restart: always
    volumes:
        - /opt/toughrun/mysql:/var/lib/mysql

radius:
    build: .
    privileged: true
    ports:
        - "1816:1816"
        - "18162:18162"
        - "18163:18163"
    links:
        - raddb
    environment:
        - DB_TYPE=mysql
        - DB_URL=mysql://raduser:radpwd@raddb:3306/radiusd?charset=utf8
        - TIMEZONE=CST-8
        - SYSLOG_ENABLE=1
        - SYSLOG_SERVER=121.201.15.99
        - SYSLOG_PORT=514
        - SYSLOG_LEVEL=INFO
    restart: always
    volumes:
        - /opt/toughrun/toughradius:/var/toughradius

engine:
    image: "index.alauda.cn/toughstruct/toughengine"
    privileged: true
    links:
        - radius
    ports:
        - "1812:1823/udp"
        - "1813:1813/udp"
        - "1815:1815"
    environment:
        - TIMEZONE=CST-8
        - API_URL=http://radius:1816/api
        - API_SECRET=LpWE9AtfDPQ3ufXBS6gJ37WW8TnSF920
        - SYSLOG_ENABLE=1
        - SYSLOG_SERVER=121.201.15.99
        - SYSLOG_PORT=514
        - SYSLOG_LEVEL=INFO
    restart: always
    volumes:
        - /home/toughrun/toughengine:/var/toughengine


nginx:
    image: "index.alauda.cn/toughstruct/docker-nginx"
    ports:
        - "8080:80"
        - "8443:443"
    links:
        - radius
    restart: always
    volumes:
        - /opt/toughrun/nginx/cache:/var/cache/nginx
        - /opt/toughrun/nginx/log:/var/log/nginx
        - /opt/toughrun/nginx/etc/nginx.conf:/etc/nginx.conf
        - /opt/toughrun/nginx/etc/nginx/conf.d/toughradius-nginx.conf:/etc/nginx/conf.d/toughradius-nginx.conf


