raddb:
    image: "index.alauda.cn/toughstruct/mysql"
    privileged: true
    expose:
        - "3306"
    environment:
        - MYSQL_USER=raduser
        - MYSQL_PASSWORD=radpwd
        - MYSQL_DATABASE=radiusd
        - MYSQL_ROOT_PASSWORD=radroot
    restart: always
    volumes:
        - /home/toughrun/mysql:/var/lib/mysql

radius:
    image: "index.alauda.cn/toughstruct/toughradius:v2"
    command: pypy /opt/toughengine/toughctl --admin
    expose:
        - "1816"
        - "18162"
        - "18163"
    links:
        - raddb:raddb
    environment:
        - DB_TYPE=mysql
        - DB_URL=mysql://raduser:radpwd@raddb:3306/radiusd?charset=utf8
        - TCP_PORTS=18162,18163
    restart: always
    volumes:
        - /home/toughrun/toughradius:/var/toughradius

haradius:
    image: "index.alauda.cn/tutum/haproxy"
    links:
        - radius:radius
    ports:
        - "1816:80"
        - "18162:18162"
        - "18163:18163"

engine:
    image: "index.alauda.cn/toughstruct/toughengine"
    command: pypy /opt/toughengine/toughctl --standalone
    ports:
        - "1812:1823/udp"
        - "1813:1813/udp"
        - "1815:1815"
    environment:
        - TIMEZONE=CST-8
        - API_URL=http://0.0.0.0:8080/api
        - API_SECRET=LpWE9AtfDPQ3ufXBS6gJ37WW8TnSF920
        - SYSLOG_ENABLE=1
        - SYSLOG_SERVER=121.201.15.99
        - SYSLOG_PORT=514
        - SYSLOG_LEVEL=INFO
    restart: always
    volumes:
        - /home/toughrun/toughengine:/var/toughengine
